gamma: 150
beta: 500
pieta: 0.1
hidden_dim: 4096
z_dim: 128
n_clusters: 100
epo: 100
bs: 1500
lr: 1.e-4
lr_c: 1.e-4
eps: 0.1
data_dir: ./data/datasets/cifar100_clip_60000.pt
data_dir_val: ./data/datasets/cifar100_clip_60000.pt
warmup: 200
save_every: 25
