gamma: 600
beta: 300
pieta: 0.13
hidden_dim: 4096
z_dim: 256
n_clusters: 20
epo: 50
bs: 1500
lr: 5.e-5
lr_c: 1.e-4
eps: 0.1
data_dir: ./data/datasets/cifar100_clip_60000.pt
data_dir_val: ./data/datasets/cifar100_clip_60000.pt
warmup: -1
save_every: 25
