gamma: 300
beta: 600
pieta: 0.175
hidden_dim: 4096
z_dim: 128
n_clusters: 10
epo: 10
bs: 1024
lr: 1.e-4
lr_c: 1.e-4
eps: 0.1
data_dir: ./data/datasets/cifar10_clip_60000.pt
data_dir_val: ./data/datasets/cifar10_clip_60000.pt
warmup: 200
save_every: 10
