gamma: 300
beta: 400
pieta: 0.1
piiter: 5
hidden_dim: 4096
z_dim: 128
n_clusters: 15
epo: 200
bs: 1024
lr: 1.e-4
lr_c: 1.e-4
eps: 0.1
data_dir: ./data/datasets/imagenetdogs_clip.pt
data_dir_val: ./data/datasets/imagenetdogs_clip.pt
warmup: -1
save_every: 25
