gamma: 75
beta: 10
pieta: 0.2
hidden_dim: 80
z_dim: 64
n_clusters: 40
epo: 5000
lr: 1.e-4
eps: 0.1
data_dir: ./data/datasets/ORL_32x32.mat
warmup: 100
save_every: 5000
channels: [1, 3, 3, 5]
kernels: [3, 3, 3]