gamma: 200
beta: 400
pieta: 0.1
hidden_dim: 4096
z_dim: 256
n_clusters: 200
epo: 100
bs: 1500
lr: 1.e-4
lr_c: 1.e-4
eps: 0.1
data_dir: ./data/datasets/tinyimagenet_train_clip.pt
data_dir_val: ./data/datasets/tinyimagenet_val_clip.pt
warmup: -1
save_every: 25
